=== IntersectMBO/cardano-config/cardano-config/schemas/TestingConfig.schema.json
{
    "$id": "https://raw.githubusercontent.com/IntersectMBO/cardano-base/master/cardano-config/schemas/TestingConfig.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "TestingConfiguration",
    "properties": {
        "DijkstraGenesisFile": {
            "description": "Path to the file",
            "format": "path",
            "title": "DijkstraGenesisFile",
            "type": "string"
        },
        "DijkstraGenesisHash": {
            "description": "Hash of the file\nBlake2b_256 hash",
            "title": "DijkstraGenesisHash",
            "type": "string"
        },
        "ExperimentalHardForksEnabled": {
            "default": false,
            "description": "Enable the experimental eras",
            "title": "ExperimentalHardForksEnabled",
            "type": "boolean"
        },
        "TestAllegraHardForkAtEpoch": {
            "description": "Force the Allegra hard fork at this epoch",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestAllegraHardForkAtEpoch",
            "type": "integer"
        },
        "TestAllegraHardForkAtVersion": {
            "description": "Force the Allegra hard fork at this protocol version",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestAllegraHardForkAtVersion",
            "type": "integer"
        },
        "TestAlonzoHardForkAtEpoch": {
            "description": "Force the Alonzo hard fork at this epoch",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestAlonzoHardForkAtEpoch",
            "type": "integer"
        },
        "TestAlonzoHardForkAtVersion": {
            "description": "Force the Alonzo hard fork at this protocol version",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestAlonzoHardForkAtVersion",
            "type": "integer"
        },
        "TestBabbageHardForkAtEpoch": {
            "description": "Force the Babbage hard fork at this epoch",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestBabbageHardForkAtEpoch",
            "type": "integer"
        },
        "TestBabbageHardForkAtVersion": {
            "description": "Force the Babbage hard fork at this protocol version",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestBabbageHardForkAtVersion",
            "type": "integer"
        },
        "TestConwayHardForkAtEpoch": {
            "description": "Force the Conway hard fork at this epoch",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestConwayHardForkAtEpoch",
            "type": "integer"
        },
        "TestConwayHardForkAtVersion": {
            "description": "Force the Conway hard fork at this protocol version",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestConwayHardForkAtVersion",
            "type": "integer"
        },
        "TestDijkstraHardForkAtEpoch": {
            "description": "Force the Dijkstra hard fork at this epoch",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestDijkstraHardForkAtEpoch",
            "type": "integer"
        },
        "TestDijkstraHardForkAtVersion": {
            "description": "Force the Dijkstra hard fork at this protocol version",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestDijkstraHardForkAtVersion",
            "type": "integer"
        },
        "TestMaryHardForkAtEpoch": {
            "description": "Force the Mary hard fork at this epoch",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestMaryHardForkAtEpoch",
            "type": "integer"
        },
        "TestMaryHardForkAtVersion": {
            "description": "Force the Mary hard fork at this protocol version",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestMaryHardForkAtVersion",
            "type": "integer"
        },
        "TestShelleyHardForkAtEpoch": {
            "description": "Force the Shelley hard fork at this epoch",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestShelleyHardForkAtEpoch",
            "type": "integer"
        },
        "TestShelleyHardForkAtVersion": {
            "description": "Force the Shelley hard fork at this protocol version",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "TestShelleyHardForkAtVersion",
            "type": "integer"
        }
    },
    "title": "TestingConfig",
    "type": "object"
}

=== IntersectMBO/cardano-config/test/examples/testing.json
{
    "$schema": "https://raw.githubusercontent.com/IntersectMBO/cardano-config/v1/schemas/TestingConfig.schema.json",
    "ExperimentalHardForksEnabled": true,
    "DijkstraGenesisFile": "dijkstra-genesis.json",
    "DijkstraGenesisHash": "56c06ff0f668c584fc54fa3cee92dd5e121b67696924ac3b01b5aec9ecf95b78",
    "TestShelleyHardForkAtEpoch": 2
}
