=== IntersectMBO/cardano-config/schemas/ShelleyGenesis.schema.json
{
    "$id": "https://raw.githubusercontent.com/IntersectMBO/cardano-config/main/schemas/ShelleyGenesis.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "ShelleyGenesis",
    "properties": {
        "activeSlotsCoeff": {
            "description": "Active slot coefficient\nactiveSlotsCoeff",
            "title": "activeSlotsCoeff"
        },
        "epochLength": {
            "description": "Epoch length in slots",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "epochLength",
            "type": "integer"
        },
        "extraConfig": {
            "description": "Extra streaming-injection configuration\nShelleyExtraConfig",
            "title": "extraConfig"
        },
        "genDelegs": {
            "additionalProperties": {
                "description": "GenDelegPair",
                "properties": {
                    "delegate": {
                        "description": "Delegate key hash",
                        "title": "delegate",
                        "type": "string"
                    },
                    "vrf": {
                        "description": "Delegate VRF key hash",
                        "title": "vrf",
                        "type": "string"
                    }
                },
                "required": [
                    "vrf",
                    "delegate"
                ],
                "type": "object"
            },
            "description": "Genesis key delegations",
            "title": "genDelegs",
            "type": "object"
        },
        "initialFunds": {
            "additionalProperties": {
                "type": "integer"
            },
            "description": "Initial UTxO funds",
            "title": "initialFunds",
            "type": "object"
        },
        "maxKESEvolutions": {
            "description": "Maximum KES evolutions",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "maxKESEvolutions",
            "type": "integer"
        },
        "maxLovelaceSupply": {
            "description": "Maximum lovelace supply",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "maxLovelaceSupply",
            "type": "integer"
        },
        "networkId": {
            "description": "Network id",
            "enum": [
                "Testnet",
                "Mainnet"
            ],
            "title": "networkId",
            "type": "string"
        },
        "networkMagic": {
            "description": "Network magic",
            "maximum": 4294967295,
            "minimum": 0,
            "title": "networkMagic",
            "type": "integer"
        },
        "protocolParams": {
            "description": "Initial protocol parameters\nShelleyPParams",
            "properties": {
                "a0": {
                    "description": "Pool influence\na0",
                    "title": "a0"
                },
                "decentralisationParam": {
                    "description": "Decentralisation parameter\ndecentralisationParam",
                    "title": "decentralisationParam"
                },
                "eMax": {
                    "description": "Epoch bound on pool retirement",
                    "maximum": 4294967295,
                    "minimum": 0,
                    "title": "eMax",
                    "type": "integer"
                },
                "extraEntropy": {
                    "description": "Extra entropy",
                    "title": "extraEntropy"
                },
                "keyDeposit": {
                    "description": "The amount of a key registration deposit",
                    "maximum": 1.8446744073709551615e19,
                    "minimum": 0,
                    "title": "keyDeposit",
                    "type": "integer"
                },
                "maxBlockBodySize": {
                    "description": "Maximum block body size",
                    "maximum": 4294967295,
                    "minimum": 0,
                    "title": "maxBlockBodySize",
                    "type": "integer"
                },
                "maxBlockHeaderSize": {
                    "description": "Maximum block header size",
                    "maximum": 65535,
                    "minimum": 0,
                    "title": "maxBlockHeaderSize",
                    "type": "integer"
                },
                "maxTxSize": {
                    "description": "Maximum transaction size",
                    "maximum": 4294967295,
                    "minimum": 0,
                    "title": "maxTxSize",
                    "type": "integer"
                },
                "minFeeA": {
                    "description": "The constant factor for the minimum fee calculation",
                    "maximum": 1.8446744073709551615e19,
                    "minimum": 0,
                    "title": "minFeeA",
                    "type": "integer"
                },
                "minFeeB": {
                    "description": "The linear factor for the minimum fee calculation",
                    "maximum": 1.8446744073709551615e19,
                    "minimum": 0,
                    "title": "minFeeB",
                    "type": "integer"
                },
                "minPoolCost": {
                    "description": "Minimum pool cost",
                    "maximum": 1.8446744073709551615e19,
                    "minimum": 0,
                    "title": "minPoolCost",
                    "type": "integer"
                },
                "minUTxOValue": {
                    "description": "Minimum UTxO value",
                    "maximum": 1.8446744073709551615e19,
                    "minimum": 0,
                    "title": "minUTxOValue",
                    "type": "integer"
                },
                "nOpt": {
                    "description": "Desired number of pools",
                    "maximum": 65535,
                    "minimum": 0,
                    "title": "nOpt",
                    "type": "integer"
                },
                "poolDeposit": {
                    "description": "The amount of a pool registration deposit",
                    "maximum": 1.8446744073709551615e19,
                    "minimum": 0,
                    "title": "poolDeposit",
                    "type": "integer"
                },
                "protocolVersion": {
                    "description": "Protocol version\nProtVer",
                    "properties": {
                        "major": {
                            "description": "Major protocol version",
                            "maximum": 4294967295,
                            "minimum": 0,
                            "title": "major",
                            "type": "integer"
                        },
                        "minor": {
                            "description": "Minor protocol version",
                            "minimum": 0,
                            "title": "minor",
                            "type": "integer"
                        }
                    },
                    "required": [
                        "minor",
                        "major"
                    ],
                    "title": "protocolVersion",
                    "type": "object"
                },
                "rho": {
                    "description": "Monetary expansion\nrho",
                    "title": "rho"
                },
                "tau": {
                    "description": "Treasury expansion\ntau",
                    "title": "tau"
                }
            },
            "required": [
                "protocolVersion",
                "extraEntropy",
                "decentralisationParam",
                "tau",
                "rho",
                "a0",
                "nOpt",
                "eMax",
                "poolDeposit",
                "keyDeposit",
                "maxBlockHeaderSize",
                "maxTxSize",
                "maxBlockBodySize",
                "minFeeB",
                "minFeeA"
            ],
            "title": "protocolParams",
            "type": "object"
        },
        "securityParam": {
            "description": "Security parameter k",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "securityParam",
            "type": "integer"
        },
        "slotLength": {
            "description": "Slot length in seconds",
            "title": "slotLength",
            "type": "number"
        },
        "slotsPerKESPeriod": {
            "description": "Slots per KES period",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "slotsPerKESPeriod",
            "type": "integer"
        },
        "staking": {
            "description": "Initial stake distribution\nShelleyGenesisStaking",
            "properties": {
                "pools": {
                    "additionalProperties": {
                        "description": "StakePoolParams"
                    },
                    "description": "Initial stake pools",
                    "title": "pools",
                    "type": "object"
                },
                "stake": {
                    "additionalProperties": {
                        "type": "string"
                    },
                    "description": "Initial stake delegation",
                    "title": "stake",
                    "type": "object"
                }
            },
            "required": [
                "stake",
                "pools"
            ],
            "title": "staking",
            "type": "object"
        },
        "systemStart": {
            "description": "System start time\nUTCTime",
            "title": "systemStart",
            "type": "string"
        },
        "updateQuorum": {
            "description": "Update quorum",
            "maximum": 1.8446744073709551615e19,
            "minimum": 0,
            "title": "updateQuorum",
            "type": "integer"
        }
    },
    "required": [
        "initialFunds",
        "genDelegs",
        "protocolParams",
        "maxLovelaceSupply",
        "updateQuorum",
        "slotLength",
        "maxKESEvolutions",
        "slotsPerKESPeriod",
        "epochLength",
        "securityParam",
        "activeSlotsCoeff",
        "networkId",
        "networkMagic",
        "systemStart"
    ],
    "title": "ShelleyGenesis",
    "type": "object"
}

=== IntersectMBO/cardano-config/test/examples/injection-genesis/shelley-genesis.json
{
  "activeSlotsCoeff": 0.05,
  "epochLength": 432000,
  "genDelegs": {},
  "initialFunds": {},
  "maxKESEvolutions": 60,
  "maxLovelaceSupply": 2010000000000000,
  "networkId": "Testnet",
  "networkMagic": 42,
  "protocolParams": {
    "a0": 0.3,
    "decentralisationParam": 0,
    "eMax": 18,
    "extraEntropy": {
      "tag": "NeutralNonce"
    },
    "keyDeposit": 400000,
    "maxBlockBodySize": 81920,
    "maxBlockHeaderSize": 1100,
    "maxTxSize": 16384,
    "minFeeA": 0,
    "minFeeB": 0,
    "minPoolCost": 0,
    "minUTxOValue": 0,
    "nOpt": 50,
    "poolDeposit": 500000000,
    "protocolVersion": {
      "major": 5,
      "minor": 0
    },
    "rho": 0.0022,
    "tau": 0.05
  },
  "securityParam": 2160,
  "slotLength": 1,
  "slotsPerKESPeriod": 129600,
  "staking": {
    "pools": {},
    "stake": {}
  },
  "systemStart": "2022-06-16T08:04:19Z",
  "updateQuorum": 5,
  "extraConfig": {
    "initialFunds": {
      "file": [
        "initial-funds.json"
      ],
      "hash": "9287594e73fc376587fa38beda535a2b3d782a637961e8edf5f131c7afc4be5d"
    },
    "stakePools": {
      "file": [
        "stake-pools.json"
      ],
      "hash": "15be7bab8f331b6a6b551583508e7ffc2dc36e3a47cbdac19b55a245162c23f1"
    }
  }
}
